# .github/workflows/deploy.yml
name: Deploy Website to GitHub Pages

on:
  push:
    branches:
      - main # Adjust if you're using a different branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Inject SEARCH_ENGINE_ID into search.html
        run: |
          sed -i 's/SEARCH_ENGINE_ID_PLACEHOLDER/${{ secrets.SEARCH_ENGINE_ID }}/g' search.html

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./ # Adjust if your static files are in a different directory
